
---
common: &common
  adapter: postgresql
  username:
  password:
  host: localhost
  timeout: 5000

development:
  <<: *common
  database: tabsquared_dev

 
test:
  <<: *common
  database: tabsquared_test


production:
  <<: *common
  database: tabsquared
